Added mkdocs into the command to deploy the docs
Tea-n-Tech/professional-python pull request #6
Opened 2022-11-05 17:15 UTC by manuel1618

Hey man,

was playing around with the docs and found out that the mkdocs command was missing, or could that be a windows thing? Wdyt?

2022-11-05 20:43 UTC, codie3611 requested changes
Can you change that also in all following lessons plz?

2022-11-06 14:50 UTC, manuel1618 commented
> Can you change that also in all following lessons plz?

As far as I can see it, it was the only place that needed change. 
It was in the readme section only, code not affected. Search done: "poetry run gh-deploy" - yielded no concrete results where mkdocs was missing.

2022-11-06 17:58 UTC, codie3611 approved these changes

2022-11-06 17:59 UTC, codie3611 commented
Ah I see all good then :+1:

2022-11-06 18:01 UTC, merged